---

- meta: flush_handlers

- name: mirrors | Import the mirror keys
  sudo: no
  gpg_recv:
    key: "{{ item.trusted_key }}"
    keyring: "{{ item.keyring | default('trustedkeys.gpg') }}"
    keyserver: "{{ item.keyserver | default('keys.gnupg.net') }}"
  with_items: mirrors

- name: mirrors | Create the aptly mirrors
  sudo: no
  aptly:
    subject: mirror
    verb: create
    name: "{{ item.name }}"
    uri: "{{ item.uri }}"
    distribution: "{{ item.distribution }}"
    components: "{{ item.components }}"
    architectures: "{{ item.architectures | default(None)}}"
  with_items: mirrors

- name: mirrors | Update the aptly mirrors
  sudo: no
  aptly:
    subject: mirror
    verb: update
    name: "{{ item.name }}"
    within: "{{ item.within | default(0) }}"
  with_items: mirrors

- name: mirrors | Create snapshots
  sudo: no
  aptly:
    subject: snapshot
    verb: create
    name: "{{ item.name }}"
    within: "{{ item.within | default(0) }}"
  with_items: mirrors

- name: mirrors | Publish snapshots
  sudo: no
  aptly:
    subject: publish
    verb: snapshot
    name: "{{ item.name }}"
    gpg_passphrase: "{{ mirror_gpg_password | default(None) }}"
  with_items: mirrors

- name: mirrors | Make the GPG key available
  sudo: no
  shell: "gpg --export --armor > {{ mirror_server_docroot }}/Key.gpg"

- name: mirrors | Configure webserver
  template:
    src: mirrors.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart webserver
