---

- meta: flush_handlers

- name: packages | Install system packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - aptly
    - gnupg2
    - python-dev
    - python-pip
    - libffi-dev
    - git-core
    - apache2

- name: packages | Install python packages
  pip:
    name={{ item }}
    state=latest
  with_items:
    - requests[security]
    - pip
    - python-gnupg
    - pexpect
    - "git+https://github.com/badi/pxul.git@v2.0#egg=pxul"

